# ansible-playbook -i inventory.yml --vault-id default@/etc/ansible_pass_private deploy.yml --diff --extra-vars '{"tag": "v0.4.6"}'

- name: Deploy
  hosts: dev_server
  become: true
  gather_facts: false

  vars_files:
      - "{{ playbook_dir }}/vars.yml"

  tasks:
      - name: Install Docker SDK
        apt:
            name: python3-docker
            state: present

      - name: Login to Docker Hub
        docker_login:
            username: "{{ docker_hub_username }}"
            password: "{{ docker_hub_password }}"

      - name: Start new website container
        docker_container:
            name: "omega-quiz"
            image: "{{ docker_hub_username }}/omega-quiz:{{ tag }}"
            state: started
            restart_policy: unless-stopped
            ports:
                - "3333:3000"

      - name: Configure Caddyfile
        blockinfile:
            path: /root/Caddyfile
            create: true
            marker: "# {mark} ANSIBLE MANAGED OMEGA QUIZ BLOCK"
            block: |
                omega-quiz.linode.djupvik.dev {
                  reverse_proxy 127.0.0.1:3333 {
                    transport http {
                      keepalive 60m
                      keepalive_interval 10s
                    }
                  }
                }

      - name: (Re)start Caddy container
        docker_container:
            name: caddy
            image: caddy:latest
            state: started
            restart_policy: always
            network_mode: host
            restart: true
            volumes:
                - "/root/Caddyfile:/etc/caddy/Caddyfile:ro"
